add a new test case for LRO patch with 200
Azure/autorest.testserver pull request #298
Opened 2021-08-05 06:36 UTC by ArcturusZhang

2021-08-05 22:07 UTC, deyaaeldeen commented
Could you please having the actual change in a separate commit/PR from the formatting ones?

2021-08-06 07:10 UTC, ArcturusZhang commented
Hi @deyaaldeen thank you for your suggestion. I just reverted the format changes, please take a look again

2021-08-06 18:05 UTC, deyaaeldeen reviewed
@ArcturusZhang thanks! I see, do we know if there is an azure service that support patching LROs?

@lmazuel it looks good to me, but could you please take a look?

2021-08-09 02:59 UTC, ArcturusZhang commented
> @ArcturusZhang thanks! I see, do we know if there is an azure service that support patching LROs?
> 
> @lmazuel it looks good to me, but could you please take a look?

We have a lot of this kind of cases in the compute RP. For instance, the patch for virtual machines: https://github.com/Azure/azure-rest-api-specs/blob/aa9d7789d10539f808419e01833b803849f6d6f6/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json#L3175

2021-08-09 16:10 UTC, lmazuel commented
I don't think I agree with the concept of the PR, the presence of a Location header implies polling. The Compute Swagger you mention seems wrong to me, if the only acceptable answer is 200, why making it a LRO in the first place? I'm sure there is more to it than the Swagger and the Swagger is not accurate of actual PATCH return. I would be extermely surprised that Compute team is commiting that all PATCH operations on VM are instantaneous.

2021-08-09 16:10 UTC, lmazuel requested changes
Feels incorrect

2021-08-10 00:52 UTC, ArcturusZhang commented
> I don't think I agree with the concept of the PR, the presence of a Location header implies polling. The Compute Swagger you mention seems wrong to me, if the only acceptable answer is 200, why making it a LRO in the first place? I'm sure there is more to it than the Swagger and the Swagger is not accurate of actual PATCH return. I would be extermely surprised that Compute team is commiting that all PATCH operations on VM are instantaneous.

I am not sure with the compute swagger - we could follow up on that. But after I run the real case again, I found it actually has an `Azure-AsyncOperation` header instead of `Location` header and I have changed that in my PR.

2021-08-10 01:01 UTC, m-nash requested changes

2021-08-10 20:03 UTC, lmazuel commented on legacy/routes/lros.js
> +    var headers = {
To be consistent with the testserver naming convention, the test `LROPatchInlineComplete` of url `/patch/200/succeeded` should not have headers defined, like you can see the parallel in PUT:
https://github.com/Azure/autorest.testserver/blob/ab118a361d2b98697ed4b6ba9450348beeaf6c3d/legacy/routes/lros.js#L55-L58

2021-08-10 20:04 UTC, lmazuel commented on legacy/routes/lros.js
> +  router.patch("/patch/200/succeeded/nostate", function (req, res, next) {
You may just waive this improbably never seen scenario for now, or if you keep it use the PUT naming convention too:
https://github.com/Azure/autorest.testserver/blob/ab118a361d2b98697ed4b6ba9450348beeaf6c3d/legacy/routes/lros.js#L65-L68

2021-08-10 20:57 UTC, lmazuel commented
@ArcturusZhang @m-nash to be faithful of what you want, please do a new test called something like:

```
  router.patch("/patch/200/succeeded/ignoreheaders", function (req, res, next) {
    coverage["LROPatchInlineCompleteIgnoreHeaders"]++;
    var headers = {
      'Azure-AsyncOperation': "http://localhost/fakeurl_crash_with_404_you_should_not_call_this",
    };
    res.set(headers).status(200).type("json")
      .end('{ "properties": { "provisioningState": "Succeeded"}, "id": "100", "name": "foo" }');
  });
```

This way you make the point of the test more obvious: runtime should ignore headers if the situation is 200/Succeeded. If they don't this will crash since the polling will raise from a 404.

2021-08-11 23:11 UTC, lmazuel approved these changes

2021-08-11 23:12 UTC, lmazuel commented
@ArcturusZhang you need to update the bugfix version number in your PR (that's the way the CI is setup) from 31 to 32. On merge, the version 32 will get released automatically. But if you don't increment the number, you won't get a release.

https://github.com/Azure/autorest.testserver/blob/2d144ee8c1b5632b61f479650c2b7e6ef816bc55/package.json#L3

2021-08-12 01:15 UTC, m-nash approved these changes

2021-08-12 01:15 UTC, merged